# SPDX-License-Identifier: Apache-2.0
#
# AOSPEXT project (https://github.com/GloDroid/aospext)
#
# Copyright (C) 2023 The GloDroid project

include $(CLEAR_VARS)

AOSPEXT_ARCH_PREFIX :=
AOSPEXT_BUILD_SYSTEM :=
AOSPEXT_EXTRA_DEPS :=
AOSPEXT_GEN_PKGCONFIGS :=
AOSPEXT_GEN_TARGETS :=
AOSPEXT_INTERNAL_BUILD_TARGET :=
AOSPEXT_OUT_DIR :=
AOSPEXT_PROJECT_NAME :=
AOSPEXT_EXPORT_INSTALLED_INCLUDE_DIRS :=
AOSPEXT_VENDOR_MODULE := true
FFMPEG_DEFINITIONS :=
MESON_BUILD_ARGUMENTS :=
CMAKE_ARGUMENTS :=
CMAKE_SRC_SUBDIR :=
